# Site settings
title: Open Infrastructure Services, LLC
header-img: img/home-bg.jpg
email: jeff@openinfrastructure.co
description: > # this means to ignore newlines until "baseurl:"
  Open Infrastructure Services, LLC provides IT infrastructure consulting
  services.  Founded by Jeff McCune, an experienced Linux systems administrator
  and software developer with over a 10 years of industry experience.
  Specializing in Puppet, service oriented architecture, agile methodologies,
  and DevOps practices.
baseurl: ""
url: "https://www.openinfrastructure.co"
twitter_username: "0xEFF"
github_username: jeffmccune
facebook_username: mccune.jeff
linkedin_username: jeffmccune
email_username: jeff@openinfrastructure.co
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
